name: mapeditor
description: Map editor for Forged to Battle
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  backend:
    path: ../backend
  gesture_x_detector: ^1.1.1
  shared_preferences: 2.0.15
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true